name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.3"
        - "24.2"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: CONFIGURE BAZEL
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        cat << EOF >> .bazelrc
          build --//:erlang_version=${{ matrix.otp }}
          build --//:erlang_home=${ERLANG_HOME}

          build --incompatible_strict_action_env
        EOF
    - name: TEST
      run: |
        bazelisk test //...
    - name: RESOVLE TEST LOGS PATH
      run: |
        echo "::set-output name=LOGS_PATH::$(readlink -f bazel-testlogs)"
      id: resolve-test-logs-path
    - name: CAPTURE TEST LOGS
      uses: actions/upload-artifact@v2
      with:
        name: bazel-testlogs-${{matrix.otp}}
        path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}/*
  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.3"
        - "24.2"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: CONFIGURE BAZEL
      shell: bash
      run: |
        ERL_PATH="$(which erl)"
        cat << EOF >> .bazelrc
          startup --windows_enable_symlinks
          build --enable_runfiles

          build --//:erlang_version=${{ matrix.otp }}
          build --//:erlang_home="${ERL_PATH/\/bin\/erl/}"

          build --incompatible_strict_action_env
        EOF
        cat .bazelrc
    - name: TEST
      run: |
        bazelisk test //...
    #! https://github.com/actions/upload-artifact/issues/240
    #! - name: RESOVLE TEST LOGS PATH
    #!   run: |
    #!     Set-Variable -Name logs_path -Value (Get-Item bazel-testlogs).Target
    #!     Write-Output "::set-output name=LOGS_PATH::$logs_path"
    #!   id: resolve-test-logs-path
    #! - name: CAPTURE TEST LOGS
    #!   uses: actions/upload-artifact@v2
    #!   with:
    #!     name: bazel-testlogs-${{matrix.otp}}
    #!     path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}
  test-bzlmod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.3"
        - "24.2"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: CONFIGURE BAZEL
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        cat << EOF >> .bazelrc
          build --//:erlang_version=${{ matrix.otp }}
          build --//:erlang_home=${ERLANG_HOME}

          build --incompatible_strict_action_env
        EOF
    - name: TEST
      run: |
        bazelisk test //... --experimental_enable_bzlmod
    - name: RESOVLE TEST LOGS PATH
      run: |
        echo "::set-output name=LOGS_PATH::$(readlink -f bazel-testlogs)"
      id: resolve-test-logs-path
    - name: CAPTURE TEST LOGS
      uses: actions/upload-artifact@v2
      with:
        name: bazel-testlogs-bzlmod-${{matrix.otp}}
        path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}/*
