name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.2"
        - "24.0"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: ${{ matrix.otp }}
    - name: CONFIGURE BAZEL
      run: |
        ERLANG_HOME="$(dirname $(dirname $(which erl)))"
        cat << EOF >> .bazelrc
          build --//:erlang_version=${{ matrix.otp }}
          build --//:erlang_home=${ERLANG_HOME}

          build --incompatible_strict_action_env
        EOF
    - name: TEST
      run: |
        bazelisk test //...
    - name: RESOVLE TEST LOGS PATH
      run: |
        echo "::set-output name=LOGS_PATH::$(readlink -f bazel-testlogs)"
      id: resolve-test-logs-path
    - name: CAPTURE TEST LOGS
      uses: actions/upload-artifact@v2-preview
      with:
        name: bazel-testlogs-${{matrix.otp}}
        path: ${{ steps.resolve-test-logs-path.outputs.LOGS_PATH }}/*
